spring:
  application:
    name: Quase Pokedex
  datasource:
    url: jdbc:h2:mem:pokemons
    username: mestrePokemon
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console